#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_COLOR_DEPTH 24
#define LV_MEM_SIZE (64 * 1024)
#define LV_MEM_POOL_EXPAND_SIZE (512 * 1024)
#define LV_USE_OS LV_OS_NONE
#define LV_GRADIENT_MAX_STOPS 4
#define LV_USE_DRAW_SW 1
#define LV_DRAW_SW_COMPLEX 1
#define LV_USE_CANVAS 1
#define LV_USE_LABEL 1
#define LV_USE_IMAGE 1
#define LV_USE_THEME_DEFAULT 0
#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1
#endif
